logging:
  level: INFO
  loggers:
    drop-wiz: DEBUG

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1

  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
#hibernate:
#  dialect: org.hibernate.dialect.H2Dialect